{
 "title": "AWS EKS Cost Optimization helper",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "mem_weight",
    "label": "Memory weight",
    "query": "0,0.1,0.2,0.3,0.4,0.5,0.6.,0.7,0.8,0.9,1"
   },
   {
    "name": "cpu_weight",
    "label": "CPU wight",
    "query": "0,0.1,0.2,0.3,0.4,0.5,0.6.,0.7,0.8,0.9,1"
   }
  ]
 },
 "panels": [
  {
   "title": "Resources allocation per worker nodes",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",service=\"prometheus-kube-state-metrics\"}) by (node) / on (node) kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"}",
     "legendFormat": "CPU Requests Commitment {{node}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",service=\"prometheus-kube-state-metrics\"}) by (node) / on (node) kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kube_node_status_capacity{resource=\"pods\",job=\"kube-state-metrics\"} - on (node) count(kube_pod_info{created_by_kind!=\"Job\",created_by_kind!=\"\"}) by (node))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",service=\"prometheus-kube-state-metrics\"}) by (node) / on (node) kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",service=\"prometheus-kube-state-metrics\"}) by (node) / on (node) kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall cluster Efficiency (Approximately)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((((avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (container)) * $cpu_weight) + ((avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests) by (container)) * $mem_weight)) / ($cpu_weight + $mem_weight))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pods stability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-round(count(kube_pod_container_status_restarts_total{service=\"prometheus-kube-state-metrics\"}>0) / count(kube_pod_container_status_restarts_total{service=\"prometheus-kube-state-metrics\"}) * 100,1)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod restarts total",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}[$__range]) * on (pod) group_left (workload) namespace_workload_pod:kube_pod_owner:relabel) by (workload)>0",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}[10m]) * on (pod) group_left (workload) namespace_workload_pod:kube_pod_owner:relabel >0",
     "legendFormat": "Restarts {{workload}}"
    },
    {
     "expr": "(kube_pod_container_status_last_terminated_reason{reason=~\"OOMKilled|CrashLoopBackOff\"}  * on (pod) group_left (workload) namespace_workload_pod:kube_pod_owner:relabel) * -1",
     "legendFormat": "OOMKilled {{workload}}"
    }
   ]
  },
  {
   "title": "Overall Container efficiency",
   "type": "table",
   "gridPos": { "h": 26, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (container)) * $cpu_weight) + ((avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests) by (container)) * $mem_weight)) / ($cpu_weight + $mem_weight)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requests (cluster-wise)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "CPU Requests Commitment"
    }
   ]
  },
  {
   "title": "Memory Requests (cluster-wise)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "Memory Requests Commitment"
    }
   ]
  },
  {
   "title": "CPU Limits (cluster-wise)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "CPU Limits Commitment"
    }
   ]
  },
  {
   "title": "Memory Limits (cluster-wise)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "Memory Limits Commitment"
    }
   ]
  },
  {
   "title": "CPU Requests efficiency",
   "type": "table",
   "description": "The value shows cpu requests to actual usage difference. Greater value means lower difference. ",
   "gridPos": { "h": 19, "w": 5, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "MEM Requests efficiency",
   "type": "table",
   "gridPos": { "h": 19, "w": 5, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttling >2%",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 3, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}[$__rate_interval])) by (container) /avg(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}[$__rate_interval])) by (container)) >0.019",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM Limits efficiency <20% and >80%",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (container))<0.2",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (container))>0.8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg CPU Quota (per deployment)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container) / 100 * 40) + avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  },
  {
   "title": "Avg Memory Quota (per deployment)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container) /100 * 20) +avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container) /100 * 70) +avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "avg(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "avg(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "avg(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)"
    }
   ]
  },
  {
   "title": "Per container CPU Usage ${pod}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "repeat": "pod",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", cluster=\"$cluster\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "avg(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /avg(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) / avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      }
     ]
    }
   ]
  },
  {
   "title": "Per container Memory Usage ${pod}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "repeat": "pod",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (WSS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "avg(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)"
      },
      {
       "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container) / avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "avg(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container != \"\", container != \"POD\"}) by (container)"
      },
      {
       "expr": "avg(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container != \"\", container != \"POD\"}) by (container)"
      },
      {
       "expr": "avg(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container != \"\", container != \"POD\"}) by (container)"
      }
     ]
    }
   ]
  }
 ]
}